version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: node-app-nginx-proxy
    restart: always
    networks:
      - nginx-rev-proxy-sample-web-net
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - node-app

  node-app:
    build:
      context: node
    container_name: node-app
    entrypoint: sh entrypoint.sh
    networks:
      - nginx-rev-proxy-sample-db-net
      - nginx-rev-proxy-sample-web-net
    volumes:
      - ./node:/app
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=sample-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-rev-proxy-sample-db-net

networks:
  nginx-rev-proxy-sample-db-net:
    driver: bridge
  nginx-rev-proxy-sample-web-net:
    driver: bridge
